---
name: Hash-Dirty
version: 0.021
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
abstract: Keep track of whether a hash is dirty or not
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 0
  Sub::Exporter: 0
build_requires:
  Test::Deep: 0
  Test::More: 0
provides:
  Hash::Dirty:
    file: lib/Hash/Dirty.pm
    version: 0.021
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
